# -*- coding: utf-8 -*-
"""Núcleo CD - Analisando dados com Polars.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vIRF8YK_gpP2OTuHRcp9XiGD8i-JsQC_
"""

# Importando a biblioteca polars
import polars as pl

#Lendo a o dataset winemag-data_first150k
wine = pl.read_csv('winemag-data_first150k.csv')

#imprimindo a o cabeçalho
#lendo as 10 primeiras linhas

wine.head(5)

wine.dtypes # imprimindo os tipos de dados que temos
            # por coluna, temos String, Inteiros, Float

wine.shape #estou imprimindo a quantidade de linhaxcoluna
#são 150930 linhas e 11 colunas

wine.glimpse() #outra forma de obter o formato
                #quantidade de linhas(rows) e colunas
                #tipo de cada dado do Dataset

wine.describe() # Aqui eu imprimo as métricas básicas do dataset
                # já podemos ver a quantidade de dados por colunas na primeira linha
                # observasse que algumas colunas possuem dados em suas linhas
                # por exemplo a coluna "country" possui 150925 linha preenchida das 150930
                # indicando que pode haver dados faltantes, assim como as colunas:
                #designation, price, province, region_1, region_2
                # o null informado em algumas colunas se da pelo fato de ser string

wine.null_count() # trago a quantidade de dados faltante por coluna
                  # como visto no wine.describe, confirmamos que as colunas indicadas
                  # realmente possuem dados faltantes.

nova_wine = wine.drop_nulls() # aqui estou instanciando um novo dataframe chamado nova_wine
                              # ja com as linha que contém dados nulos excluidos.

nova_wine.describe() # verificando novamente as métricas principais como describe()
                      # verificando se esta tudo certo, agora não temos mais dados nulos
                      #como pode ver em count todos os valores estão iguais
                      # com a limpeza restaram 39241 linhas

wine['country'].unique() # aqui eu só estou verificando os valores unico

wine.filter(pl.col("country") == "Brazil").select(pl.col("variety").unique()) #Aqui estou só filtrando as variedades
                                                                              # que estão no Brasil um total de 8

wine.filter((pl.col("country") == "Brazil") # aqui eu filtro por país(country)
                  & (pl.col("points") >= 90) # aqui eu filtro por nota(>=90)
                          & (pl.col("price") < 20)).select(pl.col("variety")) #aqui eu filtro por preço menor 20
                                                    #tudo isso selecionado a variedade
                                                    #porém como não obteve resultado devido a condição não ser satisfeita

wine.filter((pl.col("country") == "Brazil")
                  & (pl.col("points") >= 85)
                          & (pl.col("price") < 20)).select(pl.col("variety"))
#porém quando mudo o condição para 85 pontos, vemos que o Merlot, podemos manipular os valores para
#encontrar uma lista maior, que atenda ao requesitos

Agrupamento = wine.group_by("country", maintain_order=True).all() #aqui só estou agrupando
                                                    # agora temos 49 paíse no total

print(Agrupamento)

preçomedio = wine.group_by("country").agg(pl.col("price").mean().alias("price-medio")).sort("price-medio", descending=True).drop_nulls("price-medio")
#estou agrupando
#calculando a média
#colocando dando um nome para a coluna da média
#colocando na ordem do maior para o menor

print(preçomedio) #US-France possui o maior preço na media

nova_wine.group_by("country").agg(pl.col("price").mean().alias("price-medio")).sort("price-medio", descending=True)
#só estou verificando no dataframe limpo, não a outros dados a não ser do US
#dutante a limpeza dos valores em branco, todos os outros paises foram esxluidos

notamax = wine.group_by("variety").agg(pl.col("points").max().alias("points-max")).sort("points-max", descending=True)
#estou agrupando
#calculando a maxima
#colocando dando um nome para a coluna da maxima
#colocando na ordem do maior para o menor

print(notamax)

nota_chardonnay = (wine.filter(pl.col("variety") == "Chardonnay").group_by("variety").agg(pl.col("points").max().alias("points-max"))
)
#estou filtrando por variedade por grupo e nota maxima

print(nota_chardonnay)

pontuações_chardonnays = (wine.filter(pl.col("variety") == "Chardonnay").filter(pl.col("points") == pl.col("points").max()))
#aqui estou filtrando e calculando os valores de todo o dataset, trazendo o país, a notra e o valor

print(pontuações_chardonnays['country','points', 'price'])

precos_medios = (wine.group_by("variety").agg(pl.col("price").mean().alias("preco_medio")).sort("preco_medio", descending=True)).drop_nulls("preco_medio")
#aqui estou filtrando e calculando os valores de todo o dataset e tirando os valores vazios

print(precos_medios)

wine = wine.with_columns((pl.col("points") / pl.col("price")).alias("custo-beneficio"))
# aqui estou criando a coluna com with_columns()
# já passando o argumento que sera points/price

print(wine['points', 'price', 'custo-beneficio'])